### PR TITLE
Fixed place_data function to work with latest geosearch api

### PR DESCRIPTION
**Pull request by jewelsjacobs**

### CODE REVIEW

**Comment by spencermountain** [comment]
aww, hi julia. thank you for the kind words.
i didn't know it was possible to 'within radius:...' on the search api! coooooool!
i'm happy to work on this this week. This merge request contains a lot of stuff, and i can't believe i was foolish enough to commit the node_modules folder. let me clean things up, and figure out a way to add you as a committer, that way.
no worries making the new mod! i'm not one of those people....
will let you know how it goes in the next few days.
cheers

**Comment by spencermountain** [comment]
hey julia, i've made these geo api changes, along with a bunch of bugfixes, let me know if it's gonna do the trick?
thanks for the heads-up

**Comment by jewelsjacobs** [comment]
Can't wait to check it out!  I'll give it a whirl and let you know if I run into anything.  Thanks for looking into this so quickly.  Now if I could just get [protractor](https://github.com/angular/protractor) to approve and add [my pull request](https://github.com/angular/protractor/pull/220) I won't have to hack any node mods!

**Comment by jewelsjacobs** [comment]
place_data works like a charm!  thanks so much yet again. :)

**Pull request closed without merging**
